- name: Download and extract node-exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/{{ version }}/node_exporter-{{ version }}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: To copy node-exporter service file
  ansible.builtin.template:
    src: node-exporter.service
    dest: /etc/systemd/system/node-exporter.service

- name: Ti start node-exporter service
  ansible.builtin.systemd_service:
    name: node-exporter
    state: started
    daemon-reload: yes
    enabled: yes


