- name: To get secrets from vault
  hosts: localhost
  gather_facts: no
  tasks:
    - name: lineinfile module for vault-secret
      ansible.builtin.lineinfile:
        create: yes
        path: "{{component}}-secrets.json"
        line: "{{ lookup('community.hashi_vault.hashi_vault', 'expense-{{ env }}/{{ component }} token={{ vault_token }} url=https://vault-internal.azcart.online:8200 validate_certs=False')  }}"

    - name: lineinfile module for vault-secret
      ansible.builtin.lineinfile:
        create: yes
        path: 'common-secrets.json'
        line: "{{ lookup('community.henvashi_vault.hashi_vault', 'common/ssh token={{ vault_token }} url=https://vault-internal.azcart.online:8200 validate_certs=False')  }}"