- name: To get secrets from vault
  hosts: localhost
 # gather_facts: no
  tasks:
    - name: "{{component}} vault-secret"
      lineinfile:
        create: yes
        path: "{{component}}-secrets.json"
        line: "{{ lookup('community.hashi_vault.hashi_vault', 'expense-{{ env }}/{{ component }} token={{ vault_token }} url=https://vault-internal.azcart.online:8200 validate_certs=False')  }}"

    - name: common vault-secret
      lineinfile:
        create: yes
        path: 'common-secrets.json'
        line: "{{ lookup('community.hashi_vault.hashi_vault', 'common/ssh token={{ vault_token }} url=https://vault-internal.azcart.online:8200 validate_certs=False')  }}"


#