- name: Install Mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: To start Mysql
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: yes

- name: To set Mysql Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1