- name: Install Mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: To start Mysql
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: yes

- name: To check weather mysql root password set
  ansible.builtin.shell: echo 'show databases' |  mysql -h {{ mysqlServerIP }} -uroot -p{{ mysql_root_password }}
  register: check
  ignore_errors: yes


- name: To set Mysql Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ mysql_root_password }}
  when: check.rc == 1