format_version: 10
pipelines:
  vaultDummy:
    group: expenseAnsible
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-214f6fa:
        git: https://github.com/cDevOps78/expenseAnsibleGoCD.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          secure_variables:
            SSH_PASSWORD: "AES:C0uIVn+cYBjLM2QV+H6agg==:vng1ida0sGt4+P1Fc0NUHg=="
          environment_variables:
            env: "dev"
            Name: "CHAITHANYA"
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            job1:
              timeout: 0
              tasks:
                - exec: {command: bash, arguments: ['vaultScript.sh'], run_if: passed}
#