format_version: 10
pipelines:
  learn-ansible:
    group: defaultGroup
    display_order: -1
    materials:
      git-7e255db:
        git: https://github.com/cDevOps78/learn_ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - DEV:
        fetch_materials: true
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          sleep:
            timeout: 10
            tasks:
            - exec:
                arguments:
                - 20s
                command: sleep
                run_if: passed