format_version: 10
pipelines:
  learn-ansible:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-7e255db:
        git: https://github.com/cDevOps78/learn_ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - DEV:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          hello:
            timeout: 10
            tasks:
            - exec:
                command: sleep
                arguments:
                - 20s
                run_if: passed
          echo:
            tasks:
            - exec:
               command: echo 
               arguments:
               - "This is chaithanya"
                     

